# This workflow will scrap GitHub trending projects daily.
name: parallel-task-clean-pre

on:
  push:
    branches:
#      - master
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  schedule:
#     run on every hour
#     - cron: "0 * * * *"
#     run on every 3 hour
#     - cron: "0 */3 * * *"
#     run on every 15 min
#     - cron: "*/45 * * * *"
#     run on 0 and 12 clock
    - cron: "0 2,12 * * *"
env:
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASS: ${{ secrets.REDIS_PASS }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install redis

    - name: Run Run love-you-more-than
      run: |
        sudo -E python3 main.py clean